[[bin]]
name = "Sun"
path = "Source/Sun.rs"

[build-dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149" }
toml = { version = "0.9.11" }

[dependencies]
Echo = { version = "0.0.1", path = "../Echo" }
async-trait = "0.1.89"
futures = { version = "0.3.31" }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0" }
tokio-tungstenite = "0.28.0"
unbug = { version = "0.4.0" }

[features]
default = []

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
default-run = "Sun"
description = "Sun ☀️"
edition = "2024"
license-file = "LICENSE"
name = "Sun"
publish = false
repository = "https://github.com/CodeEditorLand/Sun.git"
version = "0.0.1"
